# Generated by Django 3.1.7 on 2021-02-26 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intraApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='partners',
        ),
        migrations.AlterField(
            model_name='account',
            name='company_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intraApp.company'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingsCollection', to='intraApp.company'),
        ),
        migrations.CreateModel(
            name='CustomUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('userType', models.CharField(max_length=200)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intraApp.company')),
            ],
        ),
    ]
