# Generated by Django 3.1.7 on 2021-02-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intraApp', '0002_auto_20210226_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuse',
            name='userType',
        ),
    ]
