# Generated by Django 3.1.7 on 2021-02-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intraApp', '0003_remove_customuse_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuse',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customuse',
            name='last_name',
        ),
    ]
